// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnpqwozmraukbxpkhcio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZucHF3b3ptcmF1a2J4cGtoY2lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NTM3NDUsImV4cCI6MjA2NzIyOTc0NX0.YU_ZeZC3KNX60NGqYfhQTWVmfKrCG1gFPFZ_EbbBVPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});